name: Android CI
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.8.0
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Unit Test Stacktrace
        run: bash ./gradlew testDebugUnitTest --stacktrace

      - name: Test Report
        uses: dorny/test-reporter@v1.6.0
        if: ${{ always() }}
        with:
          name: Tests Output
          path: ValidatorTest.kt
          reporter: java-junit
          fail-on-error: true
