name: Android CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1

      - name: User Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Java JDK
        uses: actions/setup-java@v3.8.0
        with:
          java-version: 11

      - name: Unit Test
        run: ./gradlew testDebugUnitTest
        
