name: Android Test
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.8.0
        with:
          java-version: 11
          distribution: 'temurin'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        
      - name: Build and test
        run: |
          bash ./gradlew testDebugUnitTest --stacktrace
        
      - name: Capture error report
        if: always()
        run: |
          adb logcat -d > logcat.txt
          
      - name: Upload error report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: error-report
          path: logcat.txt

      - name: Send file to discord channel
        if: always()
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: "https://discord.com/api/webhooks/1052064972210978859/HeAxsPsmMz48s-W-ILTCdnRVYPkuNzTsnMEonOIWbw1HrDZNP0hBHL7EOP78VGWwJwDH"
        with:
          args: logcat.txt
