name: Test
on:
  push:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.2.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.8.0
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Stacktrace
        run: bash ./gradlew testDebugUnitTest --stacktrace

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: always()

#       - name: Discord notification
#         if: always()
#         env:
#           DISCORD_WEBHOOK: "https://discord.com/api/webhooks/1051738321249894460/IXHDo5MdGSQ6rhD4xmt0dNG0QWVomgrh_r718WGwriViHU0n8sahvfdMbCLzB4suoF-_"
#         uses: Ilshidur/action-discord@master
#         with:
#           args: "@everyone **Failed Unit"

#       - name: Send file to discord channel
#         if: always()
#         uses: sinshutu/upload-to-discord@master
#         env:
#           DISCORD_WEBHOOK: "https://discord.com/api/webhooks/1051738321249894460/IXHDo5MdGSQ6rhD4xmt0dNG0QWVomgrh_r718WGwriViHU0n8sahvfdMbCLzB4suoF-_"
#         with:
#           args: ./app/results.bin
          
      - name: Execute Script
        if: always()
        run: chmod +x discord-notify.sh
        
      - name: Bash
        if: always()
        run: ./discord-notify.sh
          
