name: Test
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: macOS-12 # or any other machine
    
    steps:
      - uses: actions/checkout@v3.2.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.8.0
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Stacktrace
        run: bash ./gradlew testDebugUnitTest --stacktrace

      - name: Upload Test Reports Folder
        uses: actions/upload-artifact@v3.1.1
        if: always() # IMPORTANT: Upload reports regardless of status
        with:
          name: reports
          path: app/build/test-results # path to where the xml test results are stored
        
  report:
    runs-on: ubuntu-22.04
    needs: test # The report job will run after test job
    if: always() # IMPORTANT: Execute report job regardless of status
    
    steps:
      - name: Download Test Reports Folder
        uses: actions/download-artifact@v3.0.1
        with:
          name: reports

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: always()
        
      - name: Send file to discord channel
        if: always()
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: "https://discord.com/api/webhooks/1051738321249894460/IXHDo5MdGSQ6rhD4xmt0dNG0QWVomgrh_r718WGwriViHU0n8sahvfdMbCLzB4suoF-_"
        with:
          args: results.bin
      
