name: Android Testing
on:
  push:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.2.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.8.0
        with:
          java-version: 19
          distribution: 'temurin'

      - name: Build and test
        run: bash ./gradlew testDebugUnitTest --stacktrace

      - name: Capture error report
        if: always()
        run: adb logcat -d > logcat.txt

      - name: Upload error report
        if: always()
        uses: actions/upload-artifact@v3.1.1
        with:
          name: error-reports
          path: logcat.txt
          
  Report:
    runs-on: ubuntu-latest
    needs: Test
    if: always()
    
    steps:
      - uses: actions/checkout@master
      - name: Send file to discord channel
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: "https://discord.com/api/webhooks/1052064972210978859/HeAxsPsmMz48s-W-ILTCdnRVYPkuNzTsnMEonOIWbw1HrDZNP0hBHL7EOP78VGWwJwDH"
        with:
          args: logcat.txt
