name: Test
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: macOS-12 # or any other machine
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Java JDK
        uses: actions/setup-java@v3.8.0
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Stacktrace
        run: bash ./gradlew testDebugUnitTest --stacktrace

      - name: Upload Test Reports Folder
        uses: actions/upload-artifact@v2
        if: always() # IMPORTANT: Upload reports regardless of status
        with:
          name: reports
          path: app/build/test-results # path to where the xml test results are stored
        
  report:
    runs-on: ubuntu-22.04
    needs: test # The report job will run after test job
    if: always() # IMPORTANT: Execute report job regardless of status
    
    steps:
        
      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: reports

      - name: Android Test Report
        id: test-report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: always()
      
